// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '799012862718',
    projectId: 'group-chat-d3408',
    authDomain: 'group-chat-d3408.firebaseapp.com',
    storageBucket: 'group-chat-d3408.appspot.com',
    measurementId: 'G-PLWXDNTR0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '799012862718',
    projectId: 'group-chat-d3408',
    storageBucket: 'group-chat-d3408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '799012862718',
    projectId: 'group-chat-d3408',
    storageBucket: 'group-chat-d3408.appspot.com',
    androidClientId: '799012862718-32f1feqm865h8oen9qblvabhca797h92.apps.googleusercontent.com',
    iosClientId: '799012862718-133btq4ocbpkum331pca25t1nhrfcn71.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '799012862718',
    projectId: 'group-chat-d3408',
    storageBucket: 'group-chat-d3408.appspot.com',
    androidClientId: '799012862718-32f1feqm865h8oen9qblvabhca797h92.apps.googleusercontent.com',
    iosClientId: '799012862718-nb141psnjr06p49gtuvdco2pc017id4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone.RunnerTests',
  );
}
